### ISSUE TITLE
slack API 호출

### ISSUE THREAD

**Issue by leesangdeok** [LangVE/think-alarm-bot#13]
## 완료목표

* 슬랙의 channel 생성(dev, real 분리 고려)
* 슬랙의 API 호출하여 TAB의 알림 발송

## 완료기한

2018.05.15 (화)

**Comment by leesangdeok** [comment]
slack chat.postMessage
https://slack.com/api/chat.postMessage?token={token}&channel={channel}&text=test&pretty=1

**Comment by LangVE** [comment]
https://think-alarm-bot.slack.com/messages/CAP8PSQMP/

**Comment by LangVE** [comment]
[공유 자료 WIKI](https://github.com/LangVE/think-alarm-bot/wiki/%EA%B3%B5%EC%9C%A0-%EC%9E%90%EB%A3%8C)에 
오늘 사용한 JSON Parser github 주소 올려두었습니다.
참고하세요.
