### ISSUE TITLE
XML parser(미정)를 이용하여 XML 페이지 특정항목 선택/가져오기 실습

### ISSUE THREAD

**Issue by leesangdeok** [LangVE/think-alarm-bot#8]
# 완료목표

* HttpClient를 이용하여 URL 요청 실습
* XPath를 이용하여 XML 페이지 특정항목 선택/가져오기 실습

## 완료기한

2018년 04월 13일 (금)

**Comment by LangVE** [comment]
Selenium을 이용한 URL 호출후 XML 응답을 얻는 부분을 고려하였으나
응답결과로 크롬브라우져의 렌더링된 내용을 얻어오는것을 확인하였습니다.
그래서 HttpClient를 사용하는것으로 실습을 진행하였습니다.
